# Generated by Django 2.2.7 on 2019-12-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stuinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=4)),
                ('grade', models.CharField(max_length=10)),
                ('hobby', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('addres', models.CharField(max_length=100)),
            ],
        ),
    ]
