# Generated by Django 2.2.7 on 2019-12-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stuinfo',
        ),
    ]
