# Generated by Django 2.2.7 on 2019-12-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stuinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuinfo',
            name='hobby',
        ),
    ]
