# Generated by Django 2.2.7 on 2019-12-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191202_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
