# Generated by Django 2.2.7 on 2019-12-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191202_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scuinfo_content',
            name='cday',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='scuinfo_pic',
            name='cday',
            field=models.CharField(max_length=10),
        ),
    ]
