# Generated by Django 2.2.7 on 2019-12-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191202_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scuinfo_pic',
            old_name='left_pic_url',
            new_name='hre_f',
        ),
        migrations.RenameField(
            model_name='scuinfo_pic',
            old_name='left_tit_url',
            new_name='pic_url',
        ),
        migrations.RenameField(
            model_name='scuinfo_pic',
            old_name='main_pic_url',
            new_name='titl_e',
        ),
    ]
